### ISSUE TITLE
example uses "http" instead of "https" request

### ISSUE THREAD

**Issue by CaptainOachkatzl** [tributech-solutions/tributech-dsk-api-clients#14]
in file https://github.com/tributech-solutions/tributech-dsk-api-clients/blame/develop/examples/netcore/Program.cs at line 12 `private const string nodeUrl = "http://data-api.your-node.dataspace-node.com";` "http" instead of "https" is used to create the request. this leads to an authentification error on further execution of the program.

**Comment by bergben** [comment]
@CaptainOachkatzl Good catch, thanks for reporting it! Fixed in #15
